language: java
#jdk: openjdk14 #problems with sonar-maven-plugin
branches:
  only:
    - develop
    - "/^release-[0-999].[0-999]$/"
    - master
notifications:
  email:
    recipients:
      - n.casanova@alumnos.upm.es
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=nataliacasanova -Dsonar.login=$SONAR

deploy:
  provider: heroku
  api_key: $HEROKU
  on:
    branch: master
    #app: imvg-ecosistema , por defecto igual que el nombre de artefacto de GitHub